import React, { useState } from 'react'
import { motion } from 'framer-motion'
import {
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  RadarChart, PolarGrid, PolarAngleAxis, Radar
} from 'recharts'
import toast from 'react-hot-toast'

const weeklyData = [
  { day: 'Mon', fluency: 68, sessions: 2, confidence: 65 },
  { day: 'Tue', fluency: 72, sessions: 3, confidence: 70 },
  { day: 'Wed', fluency: 75, sessions: 2, confidence: 73 },
  { day: 'Thu', fluency: 70, sessions: 4, confidence: 68 },
  { day: 'Fri', fluency: 80, sessions: 3, confidence: 78 },
  { day: 'Sat', fluency: 78, sessions: 2, confidence: 75 },
  { day: 'Sun', fluency: 83, sessions: 1, confidence: 82 }
]

const radarData = [
  { metric: 'Fluency', current: 83, previous: 68 },
  { metric: 'Confidence', current: 82, previous: 65 },
  { metric: 'Pace Control', current: 75, previous: 60 },
  { metric: 'Breathing', current: 88, previous: 72 },
  { metric: 'Onset Ease', current: 70, previous: 50 },
  { metric: 'Consistency', current: 85, previous: 70 }
]

export default function ReportsPage() {
  const [generating, setGenerating] = useState(false)
  const [selectedWeek, setSelectedWeek] = useState('current')

  const generatePDF = async () => {
    setGenerating(true)
    // Simulate PDF generation
    await new Promise(r => setTimeout(r, 2000))

    // In production, this would call the backend PDF generation endpoint
    try {
      const response = await fetch('/api/reports/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('token')}`
        },
        body: JSON.stringify({ week: selectedWeek })
      })

      if (response.ok) {
        const blob = await response.blob()
        const url = window.URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = 'fluent-ai-report.pdf'
        a.click()
        window.URL.revokeObjectURL(url)
        toast.success('Report downloaded! 📄')
      } else {
        throw new Error('Backend unavailable')
      }
    } catch {
      // Demo mode: create a simple text file
      const reportContent = generateReportText()
      const blob = new Blob([reportContent], { type: 'text/plain' })
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = 'fluent-ai-weekly-report.txt'
      a.click()
      window.URL.revokeObjectURL(url)
      toast.success('Demo report downloaded! 📄')
    }
    setGenerating(false)
  }

  const generateReportText = () => {
    return `
╔══════════════════════════════════════════════════╗
║           FLUENT AI — WEEKLY PROGRESS REPORT       ║
║                   Week of Feb 16–22, 2026           ║
╚══════════════════════════════════════════════════╝

📊 EXECUTIVE SUMMARY
━━━━━━━━━━━━━━━━━━━━
Overall Confidence Score: 82/100  (+17 from baseline)
Weekly Fluency Rate:      78%     (+10% from last week)
Anxiety Reduction:        -37%    (vs. your first week)
Practice Consistency:     6/7 days ██████░

🎯 KEY ACHIEVEMENTS THIS WEEK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✅ Completed 17 speech analysis sessions
✅ Finished 5/6 daily therapy exercises
✅ Completed 3 roleplay scenarios (Interview, Phone Call, Presentation)
✅ Maintained 14-day practice streak

📈 FLUENCY BREAKDOWN
━━━━━━━━━━━━━━━━━━━
Monday:    68%  ██████▌
Tuesday:   72%  ███████▏
Wednesday: 75%  ███████▌
Thursday:  70%  ███████
Friday:    80%  ████████
Saturday:  78%  ███████▊
Sunday:    83%  ████████▎

🧠 AI RECOMMENDATIONS FOR NEXT WEEK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Focus on phone call scenarios — your anxiety score is highest here
2. Continue easy onset practice — blocks reduced by 40% this week
3. Try the "Bouncing Technique" exercise you haven't completed yet
4. Join the Interview Prep community room for peer practice

💜 MOTIVATIONAL NOTE
━━━━━━━━━━━━━━━━━━━
"Your voice improved 17 points in one week. That's not small — that's extraordinary effort turning into real change. Keep going."
                                        — Your FluentAI Coach

Generated by FluentAI | fluent-ai.vercel.app
    `.trim()
  }

  return (
    <div className="p-6 max-w-5xl mx-auto">
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
        <div className="flex items-start justify-between">
          <div>
            <h1 className="font-display text-3xl font-bold">Weekly Reports 📄</h1>
            <p className="mt-1 text-sm" style={{ color: 'var(--text-muted)' }}>
              Download your comprehensive AI-generated progress reports to share with therapists or track offline.
            </p>
          </div>
          <motion.button
            onClick={generatePDF}
            disabled={generating}
            className="btn-primary px-6 py-3 flex items-center gap-2"
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
          >
            {generating ? (
              <>
                <span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                Generating...
              </>
            ) : '⬇️ Download Report'}
          </motion.button>
        </div>
      </motion.div>

      {/* Report preview card */}
      <div className="glass-card p-8 mb-6"
        style={{ border: '2px solid rgba(139, 92, 246, 0.2)' }}>
        <div className="flex items-center justify-between mb-6">
          <div>
            <div className="badge badge-purple mb-2 inline-flex">Week of Feb 16–22, 2026</div>
            <h2 className="font-display text-2xl font-bold">Your Progress Report</h2>
          </div>
          <div className="text-right">
            <div className="font-display text-4xl font-bold gradient-text">82</div>
            <div className="text-sm" style={{ color: 'var(--text-muted)' }}>Confidence Score</div>
            <div className="badge badge-green mt-1 inline-flex">+17 from baseline</div>
          </div>
        </div>

        {/* Key metrics row */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
          {[
            { label: 'Fluency Rate', value: '78%', change: '+10%', up: true },
            { label: 'Anxiety Reduction', value: '-37%', change: 'vs baseline', up: true },
            { label: 'Sessions', value: '17', change: '6/7 days', up: true },
            { label: 'Exercises Done', value: '5/6', change: '83% complete', up: null }
          ].map((m, i) => (
            <div key={m.label} className="p-4 rounded-xl text-center"
              style={{ background: 'rgba(139,92,246,0.05)' }}>
              <div className="font-display text-xl font-bold">{m.value}</div>
              <div className="text-xs mt-1" style={{ color: 'var(--text-muted)' }}>{m.label}</div>
              <div className={`text-xs mt-1 font-medium ${m.up ? 'text-green-500' : ''}`}>{m.change}</div>
            </div>
          ))}
        </div>

        {/* Charts */}
        <div className="grid md:grid-cols-2 gap-6 mb-8">
          <div>
            <h3 className="font-semibold mb-3 text-sm">Daily Fluency This Week</h3>
            <ResponsiveContainer width="100%" height={180}>
              <LineChart data={weeklyData}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(139,92,246,0.1)" />
                <XAxis dataKey="day" tick={{ fontSize: 11 }} />
                <YAxis domain={[50, 100]} tick={{ fontSize: 11 }} />
                <Tooltip />
                <Line type="monotone" dataKey="fluency" stroke="#8b5cf6" strokeWidth={2.5}
                  dot={{ fill: '#8b5cf6', r: 4 }} name="Fluency %" />
                <Line type="monotone" dataKey="confidence" stroke="#22c55e" strokeWidth={2}
                  dot={{ fill: '#22c55e', r: 3 }} strokeDasharray="4 4" name="Confidence" />
              </LineChart>
            </ResponsiveContainer>
          </div>
          <div>
            <h3 className="font-semibold mb-3 text-sm">Speech Profile (vs Last Week)</h3>
            <ResponsiveContainer width="100%" height={180}>
              <RadarChart data={radarData}>
                <PolarGrid stroke="rgba(139,92,246,0.2)" />
                <PolarAngleAxis dataKey="metric" tick={{ fontSize: 10 }} />
                <Radar dataKey="current" name="This Week" stroke="#8b5cf6" fill="#8b5cf6" fillOpacity={0.25} strokeWidth={2} />
                <Radar dataKey="previous" name="Last Week" stroke="#d1d5db" fill="#d1d5db" fillOpacity={0.1} strokeWidth={1.5} strokeDasharray="4 4" />
              </RadarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* AI Recommendations */}
        <div>
          <h3 className="font-semibold mb-3">🧠 AI Recommendations for Next Week</h3>
          <div className="space-y-2">
            {[
              { priority: 'High', text: 'Phone call scenarios trigger your highest anxiety — schedule 3 roleplay phone sessions this week' },
              { priority: 'High', text: 'Easy onset practice reduced your blocks by 40% — continue daily for maximum impact' },
              { priority: 'Medium', text: 'Try the Bouncing Technique exercise — it\'s the only one you haven\'t completed' },
              { priority: 'Low', text: 'Join the Interview Prep community room for peer accountability and practice' }
            ].map((r, i) => (
              <div key={i} className="flex gap-3 p-3 rounded-xl text-sm"
                style={{ background: 'rgba(134,239,172,0.06)' }}>
                <span className={`badge text-xs flex-shrink-0 ${
                  r.priority === 'High' ? 'badge-purple' : r.priority === 'Medium' ? 'badge-blue' : 'badge-green'
                }`}>{r.priority}</span>
                <span>{r.text}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Motivational quote */}
        <div className="mt-6 p-5 rounded-xl text-center"
          style={{ background: 'linear-gradient(135deg, rgba(139,92,246,0.08), rgba(125,211,252,0.08))' }}>
          <p className="font-display text-lg font-medium italic">
            "Your voice improved 17 points in one week. That's not small — that's extraordinary effort turning into real change."
          </p>
          <p className="text-sm mt-2" style={{ color: 'var(--text-muted)' }}>— Your FluentAI Coach</p>
        </div>
      </div>

      {/* Past reports */}
      <div className="glass-card p-6">
        <h2 className="font-semibold mb-4">Past Reports</h2>
        <div className="space-y-3">
          {[
            { week: 'Feb 9–15, 2026', score: 74, improvement: '+12%' },
            { week: 'Feb 2–8, 2026', score: 66, improvement: '+8%' },
            { week: 'Jan 26 – Feb 1, 2026', score: 61, improvement: '+5%' },
            { week: 'Jan 19–25, 2026', score: 58, improvement: 'Baseline' }
          ].map((r, i) => (
            <div key={i} className="flex items-center justify-between p-4 rounded-xl"
              style={{ background: 'rgba(139,92,246,0.04)' }}>
              <div>
                <div className="font-medium text-sm">{r.week}</div>
                <div className="text-xs mt-0.5" style={{ color: 'var(--text-muted)' }}>
                  Confidence Score: {r.score} · {r.improvement}
                </div>
              </div>
              <button onClick={() => toast.success('Downloading report...')}
                className="btn-secondary text-xs py-2 px-4">
                Download
              </button>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
